export const Colors = {
  light: {
    primary: '#6B5CE7',
    primaryLight: '#8B7CF7',
    primaryDark: '#5244C7',
    secondary: '#E8A87C',
    secondaryLight: '#F2C4A0',
    accent: '#41B3A3',
    accentLight: '#6DCFBF',
    background: '#FAFAFA',
    surface: '#FFFFFF',
    surfaceElevated: '#F5F3FF',
    card: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#6B7280',
    textTertiary: '#9CA3AF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    muted: '#F9FAFB',
    overlay: 'rgba(0, 0, 0, 0.5)',
    gradientStart: '#6B5CE7',
    gradientEnd: '#41B3A3',
    prayerGradientStart: '#667eea',
    prayerGradientEnd: '#764ba2',
    warmGradientStart: '#E8A87C',
    warmGradientEnd: '#F2994A',
  },
  dark: {
    primary: '#8B7CF7',
    primaryLight: '#A89CF9',
    primaryDark: '#6B5CE7',
    secondary: '#E8A87C',
    secondaryLight: '#F2C4A0',
    accent: '#6DCFBF',
    accentLight: '#8DE0D2',
    background: '#0F0F1A',
    surface: '#1A1A2E',
    surfaceElevated: '#252540',
    card: '#1E1E36',
    text: '#F0F0F5',
    textSecondary: '#9CA3AF',
    textTertiary: '#6B7280',
    border: '#2D2D4A',
    borderLight: '#252540',
    success: '#34D399',
    warning: '#FBBF24',
    error: '#F87171',
    muted: '#1A1A2E',
    overlay: 'rgba(0, 0, 0, 0.7)',
    gradientStart: '#8B7CF7',
    gradientEnd: '#6DCFBF',
    prayerGradientStart: '#667eea',
    prayerGradientEnd: '#764ba2',
    warmGradientStart: '#E8A87C',
    warmGradientEnd: '#F2994A',
  },
};

export const Typography = {
  hero: {
    fontSize: 34,
    fontWeight: '700' as const,
    lineHeight: 41,
    letterSpacing: 0.37,
  },
  title: {
    fontSize: 28,
    fontWeight: '700' as const,
    lineHeight: 34,
    letterSpacing: 0.36,
  },
  heading: {
    fontSize: 22,
    fontWeight: '600' as const,
    lineHeight: 28,
    letterSpacing: 0.35,
  },
  subheading: {
    fontSize: 18,
    fontWeight: '600' as const,
    lineHeight: 24,
    letterSpacing: -0.41,
  },
  body: {
    fontSize: 16,
    fontWeight: '400' as const,
    lineHeight: 22,
    letterSpacing: -0.32,
  },
  bodyMedium: {
    fontSize: 16,
    fontWeight: '500' as const,
    lineHeight: 22,
    letterSpacing: -0.32,
  },
  caption: {
    fontSize: 14,
    fontWeight: '400' as const,
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  captionMedium: {
    fontSize: 14,
    fontWeight: '500' as const,
    lineHeight: 20,
    letterSpacing: -0.15,
  },
  small: {
    fontSize: 12,
    fontWeight: '400' as const,
    lineHeight: 16,
    letterSpacing: 0,
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  huge: 48,
};

export const BorderRadius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  full: 9999,
};

export const Shadows = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 5,
  },
};
